# [![Opendows](https://flat.badgen.net/badge/Opendows/TWEAKERS/blue?scale=1.8)]() <img align="right" alt="stable" src="https://user-images.githubusercontent.com/171307/210727719-14b940a2-d1dc-4991-b6a4-7add74463ce8.png" width="5%" />

### 📁 [Optimizers](#optimizers-) - [Debloaters](#debloaters-) - [Setupers](#setupers-) - [Privacy](#privacy-) - [Specific](#specific-) - [Other](#other-)

> [!WARNING]
> $\color{orange}\textsf{{SORTING: Language (a>z) > License (openness) > Repository (a>z)}}$

### Optimizers [⌂](#-)
|Repository|Short description|Language|License|Last commit|
|:-:|:-:|:-:|:-:|:-:|
|[WinTune](https://github.com/tranht17/WinTune#readme)|Tweak & optimize your Windows system|[![](https://img.shields.io/github/languages/top/tranht17/WinTune?color=pink&style=flat-square)](https://github.com/tranht17/WinTune/graphs/contributors)|[![](https://flat.badgen.net/github/license/tranht17/WinTune?label=)](https://github.com/tranht17/WinTune/blob/main/LICENCE)|[![](https://img.shields.io/github/last-commit/tranht17/WinTune?style=flat-square&label=)](https://github.com/tranht17/WinTune/graphs/code-frequency)|
|[Awesome Win11](https://github.com/awesome-windows11/windows11#readme)|Windows 11 Settings, Tweaks, Scripts|[![](https://img.shields.io/github/languages/top/awesome-windows11/windows11?color=pink&style=flat-square)](https://github.com/awesome-windows11/windows11/graphs/contributors)|[![](https://flat.badgen.net/github/license/awesome-windows11/windows11?label=)](https://github.com/awesome-windows11/windows11/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/awesome-windows11/windows11?style=flat-square&label=)](https://github.com/awesome-windows11/windows11/graphs/code-frequency)|
|[Windows Scripts](https://github.com/shoober420/windows11-scripts#readme)|Windows 11 Scripts|[![](https://img.shields.io/github/languages/top/shoober420/windows11-scripts?color=pink&style=flat-square)](https://github.com/shoober420/windows11-scripts/graphs/contributors)|[![](https://flat.badgen.net/github/license/shoober420/windows11-scripts?label=)](https://github.com/shoober420/windows11-scripts/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/shoober420/windows11-scripts?style=flat-square&label=)](https://github.com/shoober420/windows11-scripts/graphs/code-frequency)|
|[Batlez Tweaks](https://github.com/Batlez/Batlez-Tweaks#readme)|A batch tweaking script that optimizes Windows 10 & 11 to provide the best gaming experience possible|[![](https://img.shields.io/github/languages/top/Batlez/Batlez-Tweaks?color=pink&style=flat-square)](https://github.com/Batlez/Batlez-Tweaks/graphs/contributors)|[![](https://flat.badgen.net/github/license/Batlez/Batlez-Tweaks?label=)](https://github.com/Batlez/Batlez-Tweaks/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/Batlez/Batlez-Tweaks?style=flat-square&label=)](https://github.com/Batlez/Batlez-Tweaks/graphs/code-frequency)|
|[Windows Essentials](https://github.com/borfei/windows-essentials#readme)|Set of tweaks to enhance your Windows experience|[![](https://img.shields.io/github/languages/top/borfei/windows-essentials?color=pink&style=flat-square)](https://github.com/borfei/windows-essentials/graphs/contributors)|[![](https://flat.badgen.net/github/license/borfei/windows-essentials?label=)](https://github.com/borfei/windows-essentials/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/borfei/windows-essentials?style=flat-square&label=)](https://github.com/borfei/windows-essentials/graphs/code-frequency)|
|[CleanWindows](https://github.com/EnesKeremAYDIN/CleanWindows#readme)|Tools to optimize Windows by removing bloatware, adjusting settings, and cleaning clutter|[![](https://img.shields.io/github/languages/top/EnesKeremAYDIN/CleanWindows?color=pink&style=flat-square)](https://github.com/EnesKeremAYDIN/CleanWindows/graphs/contributors)|[![](https://flat.badgen.net/github/license/EnesKeremAYDIN/CleanWindows?label=)](https://github.com/EnesKeremAYDIN/CleanWindows/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/EnesKeremAYDIN/CleanWindows?style=flat-square&label=)](https://github.com/EnesKeremAYDIN/CleanWindows/graphs/code-frequency)|
|[Perfect Windows 11](https://github.com/continueddev/win11-optimizer#readme)|A comprehensive toolkit of optimizations, customizations, and tweaks|[![](https://img.shields.io/github/languages/top/continueddev/win11-optimizer?color=pink&style=flat-square)](https://github.com/continueddev/win11-optimizer/graphs/contributors)|[![](https://flat.badgen.net/github/license/continueddev/win11-optimizer?label=)](https://github.com/continueddev/win11-optimizer/blob/main/LICENSE.md)|[![](https://img.shields.io/github/last-commit/continueddev/win11-optimizer?style=flat-square&label=)](https://github.com/continueddev/win11-optimizer/graphs/code-frequency)|
|[Project OptiTool](https://github.com/OptiStudioXD/OptiTool#readme)|Aims at improving your computer's performance through cleaning and managing applications, processes, and settings|[![](https://img.shields.io/github/languages/top/OptiStudioXD/OptiTool?color=pink&style=flat-square)](https://github.com/OptiStudioXD/OptiTool/graphs/contributors)|[![](https://flat.badgen.net/github/license/OptiStudioXD/OptiTool?label=)](https://github.com/OptiStudioXD/OptiTool/blob/master/LICENSE)|[![](https://img.shields.io/github/last-commit/OptiStudioXD/OptiTool?style=flat-square&label=)](https://github.com/OptiStudioXD/OptiTool/graphs/code-frequency)|
|[SionXT-TweaksWin10](https://github.com/Nerve11/SionXT-TweaksWin10#readme)|Tweaks for Windows 10 and maximize FPS, optimize Ping, reduce InputLag|[![](https://img.shields.io/github/languages/top/Nerve11/SionXT-TweaksWin10?color=pink&style=flat-square)](https://github.com/Nerve11/SionXT-TweaksWin10/graphs/contributors)|[![](https://flat.badgen.net/github/license/Nerve11/SionXT-TweaksWin10?label=)](https://github.com/Nerve11/SionXT-TweaksWin10/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/Nerve11/SionXT-TweaksWin10?style=flat-square&label=)](https://github.com/Nerve11/SionXT-TweaksWin10/graphs/code-frequency)|
|[Windows 11 Fix & Tweaks](https://github.com/kubaam/Windows-11-Fix-Tweaks#readme)|All-in-one batch file aims to streamline essential Windows 11 fixes, speed tweaks, privacy enhancements, and performance boosts|[![](https://img.shields.io/github/languages/top/kubaam/Windows-11-Fix-Tweaks?color=pink&style=flat-square)](https://github.com/kubaam/Windows-11-Fix-Tweaks/graphs/contributors)|[![](https://flat.badgen.net/github/license/kubaam/Windows-11-Fix-Tweaks?label=)](https://github.com/kubaam/Windows-11-Fix-Tweaks/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/kubaam/Windows-11-Fix-Tweaks?style=flat-square&label=)](https://github.com/kubaam/Windows-11-Fix-Tweaks/graphs/code-frequency)|
|[Windows-11-Latency-Optimization](https://github.com/NicholasBly/Windows-11-Latency-Optimization#readme)|Provides scripts to optimize Windows for enhanced latency for gaming and overall system responsiveness|[![](https://img.shields.io/github/languages/top/NicholasBly/Windows-11-Latency-Optimization?color=pink&style=flat-square)](https://github.com/NicholasBly/Windows-11-Latency-Optimization/graphs/contributors)|[![](https://flat.badgen.net/github/license/NicholasBly/Windows-11-Latency-Optimization?label=)](https://github.com/NicholasBly/Windows-11-Latency-Optimization/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/NicholasBly/Windows-11-Latency-Optimization?style=flat-square&label=)](https://github.com/NicholasBly/Windows-11-Latency-Optimization/graphs/code-frequency)|
|[WindowsTweaks](https://github.com/PantiesIsStoopid/WindowsTweaks#readme)|An app that tweaks windows to optimise performance to reduce delay|[![](https://img.shields.io/github/languages/top/PantiesIsStoopid/WindowsTweaks?color=pink&style=flat-square)](https://github.com/PantiesIsStoopid/WindowsTweaks/graphs/contributors)|[![](https://flat.badgen.net/github/license/PantiesIsStoopid/WindowsTweaks?label=)](https://github.com/NicholasBly/Windows-11-Latency-Optimization/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/PantiesIsStoopid/WindowsTweaks?style=flat-square&label=)](https://github.com/PantiesIsStoopid/WindowsTweaks/graphs/code-frequency)|
|[WinTweaks](https://github.com/Sly-Harvey/WinTweaks#readme)|Tweaks and configs for windows gaming|[![](https://img.shields.io/github/languages/top/Sly-Harvey/WinTweaks?color=pink&style=flat-square)](https://github.com/Sly-Harvey/WinTweaks/graphs/contributors)|[![](https://flat.badgen.net/github/license/Sly-Harvey/WinTweaks?label=)](https://github.com/Sly-Harvey/WinTweaks/blob/master/LICENSE)|[![](https://img.shields.io/github/last-commit/Sly-Harvey/WinTweaks?style=flat-square&label=)](https://github.com/Sly-Harvey/WinTweaks/graphs/code-frequency)|
|[Advanced Windows Tweaker](https://github.com/MartinLXXX6/Advanced-Windows-Tweaks#readme)|A versatile batch file to optimize and debloat any Windows installation|[![](https://img.shields.io/github/languages/top/MartinLXXX6/Advanced-Windows-Tweaks?color=pink&style=flat-square)](https://github.com/MartinLXXX6/Advanced-Windows-Tweaks/graphs/contributors)|[![](https://flat.badgen.net/github/license/MartinLXXX6/Advanced-Windows-Tweaks?label=)](https://github.com/MartinLXXX6/Advanced-Windows-Tweaks/issues/1)|[![](https://img.shields.io/github/last-commit/MartinLXXX6/Advanced-Windows-Tweaks?style=flat-square&label=)](https://github.com/MartinLXXX6/Advanced-Windows-Tweaks/graphs/code-frequency)|
|[Gaming OS Tweaker](https://github.com/sherifmagdy32/gaming_os_tweaker#readme)|Scripts that attempts to debloat, have low input lag, low latency, better hitreg and improved performance|[![](https://img.shields.io/github/languages/top/sherifmagdy32/gaming_os_tweaker?color=pink&style=flat-square)](https://github.com/sherifmagdy32/gaming_os_tweaker/graphs/contributors)|[![](https://flat.badgen.net/github/license/sherifmagdy32/gaming_os_tweaker?label=)](https://github.com/sherifmagdy32/gaming_os_tweaker)|[![](https://img.shields.io/github/last-commit/sherifmagdy32/gaming_os_tweaker?style=flat-square&label=)](https://github.com/sherifmagdy32/gaming_os_tweaker/graphs/code-frequency)|
|[ktweaker](https://github.com/3libs/ktweaker#readme)|A collection of handy scripts and tasks to optimize your Windows system performance|[![](https://img.shields.io/github/languages/top/3libs/ktweaker?color=pink&style=flat-square)](https://github.com/3libs/ktweaker/graphs/contributors)|[![](https://flat.badgen.net/github/license/3libs/ktweaker?label=)](https://github.com/3libs/ktweaker/issues/1)|[![](https://img.shields.io/github/last-commit/3libs/ktweaker?style=flat-square&label=)](https://github.com/3libs/ktweaker/graphs/code-frequency)|
|[Lynx Optimizer](https://github.com/caxzy/LynxOptimizer#readme)|Optimize PC for best performace, ping and reduce input delay|[![](https://img.shields.io/github/languages/top/caxzy/LynxOptimizer?color=pink&style=flat-square)](https://github.com/caxzy/LynxOptimizer/graphs/contributors)|[![](https://flat.badgen.net/github/license/caxzy/LynxOptimizer?label=)](https://github.com/caxzy/LynxOptimizer/issues/12)|[![](https://img.shields.io/github/last-commit/caxzy/LynxOptimizer?style=flat-square&label=)](https://github.com/caxzy/LynxOptimizer/graphs/code-frequency)|
|[Melody's Windows 11 Basic Optimizer](https://github.com/SheMelody/win11-basic-optimizer#readme)|Restore your system's performance after upgrading from Windows 10 to Windows 11|[![](https://img.shields.io/github/languages/top/SheMelody/win11-basic-optimizer?color=pink&style=flat-square)](https://github.com/SheMelody/win11-basic-optimizer/graphs/contributors)|[![](https://flat.badgen.net/github/license/SheMelody/win11-basic-optimizer?label=)](https://github.com/SheMelody/win11-basic-optimizer/issues/2)|[![](https://img.shields.io/github/last-commit/SheMelody/win11-basic-optimizer?style=flat-square&label=)](https://github.com/SheMelody/win11-basic-optimizer/graphs/code-frequency)|
|[Optimizing-File](https://github.com/Awneti/Optimizing-File#readme)|A windows system checking file made for optimizing your pc/laptop|[![](https://img.shields.io/github/languages/top/Awneti/Optimizing-File?color=pink&style=flat-square)](https://github.com/Awneti/Optimizing-File/graphs/contributors)|[![](https://flat.badgen.net/github/license/Awneti/Optimizing-File?label=)](https://github.com/Awneti/Optimizing-File/issues/2)|[![](https://img.shields.io/github/last-commit/Awneti/Optimizing-File?style=flat-square&label=)](https://github.com/Awneti/Optimizing-File/graphs/code-frequency)|
|[TazxPerfomance](https://github.com/TazxTweaks/TazxPerfomance#readme)|A .bat script designed to optimize the performance of Windows 10|[![](https://img.shields.io/github/languages/top/TazxTweaks/TazxPerfomance?color=pink&style=flat-square)](https://github.com/TazxTweaks/TazxPerfomance/graphs/contributors)|[![](https://flat.badgen.net/github/license/TazxTweaks/TazxPerfomance?label=)](https://github.com/TazxTweaks/TazxPerfomance/issues/1)|[![](https://img.shields.io/github/last-commit/TazxTweaks/TazxPerfomance?style=flat-square&label=)](https://github.com/TazxTweaks/TazxPerfomance/graphs/code-frequency)|
|[RyTuneX](https://github.com/rayenghanmi/RyTuneX#readme)|A comprehensive system optimization tool designed to enhance the performance, privacy, and usability of Windows systems|[![](https://img.shields.io/github/languages/top/rayenghanmi/RyTuneX?color=pink&style=flat-square)](https://github.com/rayenghanmi/RyTuneX/graphs/contributors)|[![](https://flat.badgen.net/github/license/rayenghanmi/RyTuneX?label=)](https://github.com/rayenghanmi/RyTuneX/blob/main/LICENSE.md)|[![](https://img.shields.io/github/last-commit/rayenghanmi/RyTuneX?style=flat-square&label=)](https://github.com/rayenghanmi/RyTuneX/graphs/code-frequency)|
|[QuickBoost](https://github.com/SanGraphic/QuickBoost#readme)|Automated Windows 10 / 11 Tweaking Utility|[![](https://img.shields.io/github/languages/top/SanGraphic/QuickBoost?color=pink&style=flat-square)](https://github.com/SanGraphic/QuickBoost/graphs/contributors)|[<img src="https://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-nc-sa.png" height="20">](https://github.com/SanGraphic/QuickBoost/blob/main/License)|[![](https://img.shields.io/github/last-commit/SanGraphic/QuickBoost?style=flat-square&label=)](https://github.com/SanGraphic/QuickBoost/graphs/code-frequency)|
|[GTweak](https://github.com/Greedeks/GTweak#readme)|Perfect setup of Windows 10 & Windows 11 with the choice of options you need for better convenience and performance|[![](https://img.shields.io/github/languages/top/Greedeks/GTweak?color=pink&style=flat-square)](https://github.com/Greedeks/GTweak/graphs/contributors)|[![](https://flat.badgen.net/github/license/Greedeks/GTweak?label=)](https://github.com/Greedeks/GTweak/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/Greedeks/GTweak?style=flat-square&label=)](https://github.com/Greedeks/GTweak/graphs/code-frequency)|
|[NZTS APP](https://github.com/nezhatweaks/nztsapp#readme)|A performance optimization tool designed to enhance your gaming experience by increasing frames per second (FPS) in resource-intensive games|[![](https://img.shields.io/github/languages/top/nezhatweaks/nztsapp?color=pink&style=flat-square)](https://github.com/nezhatweaks/nztsapp/graphs/contributors)|[![](https://flat.badgen.net/github/license/nezhatweaks/nztsapp?label=)](https://github.com/nezhatweaks/nztsapp/issues/4)|[![](https://img.shields.io/github/last-commit/nezhatweaks/nztsapp?style=flat-square&label=)](https://github.com/nezhatweaks/nztsapp/graphs/code-frequency)|
|[ToX Free Utility](https://github.com/ToXTweaks/ToX-Free-Utility#readme)|Unlocks hidden tweaks and optimizations to make Windows faster, smoother and more responsive|[![](https://img.shields.io/github/languages/top/ToXTweaks/ToX-Free-Utility?color=pink&style=flat-square)](https://github.com/ToXTweaks/ToX-Free-Utility/graphs/contributors)|[![](https://flat.badgen.net/github/license/ToXTweaks/ToX-Free-Utility?label=)](https://github.com/ToXTweaks/ToX-Free-Utility/issues/1)|[![](https://img.shields.io/github/last-commit/ToXTweaks/ToX-Free-Utility?style=flat-square&label=)](https://github.com/ToXTweaks/ToX-Free-Utility/graphs/code-frequency)|
|[CovEngineA](https://github.com/FulfilledCovenant/CovEngineA#readme)|An open-source semi-automated optimizations for improved overall windows 10-11 experience|[![](https://img.shields.io/github/languages/top/FulfilledCovenant/CovEngineA?color=pink&style=flat-square)](https://github.com/FulfilledCovenant/CovEngineA/graphs/contributors)|[![](https://flat.badgen.net/github/license/FulfilledCovenant/CovEngineA?label=)](https://github.com/FulfilledCovenant/CovEngineA/blob/master/LICENSE)|[![](https://img.shields.io/github/last-commit/FulfilledCovenant/CovEngineA?style=flat-square&label=)](https://github.com/FulfilledCovenant/CovEngineA/graphs/code-frequency)|
|[velocity](https://github.com/ts-at4dm/velocity#readme)|Velocity optimizes Windows by cleaning temp files, fine-tuning services, and boosting system speed for a faster, smoother experience|[![](https://img.shields.io/github/languages/top/ts-at4dm/velocity?color=pink&style=flat-square)](https://github.com/ts-at4dm/velocity/graphs/contributors)|[![](https://flat.badgen.net/github/license/ts-at4dm/velocity?label=)](https://github.com/ts-at4dm/velocity/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/ts-at4dm/velocity?style=flat-square&label=)](https://github.com/ts-at4dm/velocity/graphs/code-frequency)|
|[Windows](https://github.com/uk-dave/Windows#readme)|Various Windows OS tweaks and scripts|[![](https://img.shields.io/github/languages/top/uk-dave/Windows?color=pink&style=flat-square)](https://github.com/uk-dave/Windows/graphs/contributors)|[![](https://flat.badgen.net/github/license/uk-dave/Windows?label=)](https://github.com/uk-dave/Windows/issues/1)|[![](https://img.shields.io/github/last-commit/uk-dave/Windows?style=flat-square&label=)](https://github.com/uk-dave/Windows/graphs/code-frequency)|
|[FPS-Boost](https://github.com/therealmistake1/FPS-Boost#readme)|A batch tweaking script that optimizes your Windows 10/11 to provide the best gaming experience possible|[![](https://img.shields.io/github/languages/top/therealmistake1/FPS-Boost?color=pink&style=flat-square)](https://github.com/therealmistake1/FPS-Boost/graphs/contributors)|[![](https://flat.badgen.net/github/license/therealmistake1/FPS-Boost?label=)](https://github.com/therealmistake1/FPS-Boost/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/therealmistake1/FPS-Boost?style=flat-square&label=)](https://github.com/therealmistake1/FPS-Boost/graphs/code-frequency)|
|[GOS: Gaming Optimization Script](https://github.com/ltx0101/GOS#readme)|A comprehensive batch script created for Windows users to streamline their gaming setup, enhance network performance, repair the Windows environment, and revert changes to default settings when needed|[![](https://img.shields.io/github/languages/top/ltx0101/GOS?color=pink&style=flat-square)](https://github.com/ltx0101/GOS/graphs/contributors)|[![](https://flat.badgen.net/github/license/ltx0101/GOS?label=)](https://github.com/ltx0101/GOS/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/ltx0101/GOS?style=flat-square&label=)](https://github.com/ltx0101/GOS/graphs/code-frequency)|
|[AIO_Optimizer](https://github.com/as2648as/AIO_Optimizer#readme)|Windows 11 (All-In-One) Optimization Script|[![](https://img.shields.io/github/languages/top/as2648as/AIO_Optimizer?color=pink&style=flat-square)](https://github.com/as2648as/AIO_Optimizer/graphs/contributors)|[![](https://flat.badgen.net/github/license/as2648as/AIO_Optimizer?label=)](https://github.com/as2648as/AIO_Optimizer/blob/master/LICENSE)|[![](https://img.shields.io/github/last-commit/as2648as/AIO_Optimizer?style=flat-square&label=)](https://github.com/as2648as/AIO_Optimizer/graphs/code-frequency)|
|[Better Windows](https://github.com/HardcodeCoder/BetterWindows#readme)|A comprehensive set of tweaks to make Windows Better|[![](https://img.shields.io/github/languages/top/HardcodeCoder/BetterWindows?color=pink&style=flat-square)](https://github.com/HardcodeCoder/BetterWindows/graphs/contributors)|[![](https://flat.badgen.net/github/license/HardcodeCoder/BetterWindows?label=)](https://github.com/HardcodeCoder/BetterWindows/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/HardcodeCoder/BetterWindows?style=flat-square&label=)](https://github.com/HardcodeCoder/BetterWindows/graphs/code-frequency)|
|[Fresh-Script](https://github.com/YurinDoctrine/Fresh-Script#readme)|A tuner script works on Windows 10 and Windows 11|[![](https://img.shields.io/github/languages/top/YurinDoctrine/Fresh-Script?color=pink&style=flat-square)](https://github.com/YurinDoctrine/Fresh-Script/graphs/contributors)|[![](https://flat.badgen.net/github/license/YurinDoctrine/Fresh-Script?label=)](https://github.com/YurinDoctrine/Fresh-Script/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/YurinDoctrine/Fresh-Script?style=flat-square&label=)](https://github.com/YurinDoctrine/Fresh-Script/graphs/code-frequency)|
|[Sophia Script for Windows](https://github.com/farag2/Sophia-Script-for-Windows#readme)|The most powerful PowerShell module for fine-tuning Windows|[![](https://img.shields.io/github/languages/top/farag2/Sophia-Script-for-Windows?color=pink&style=flat-square)](https://github.com/farag2/Sophia-Script-for-Windows/graphs/contributors)|[![](https://flat.badgen.net/github/license/farag2/Sophia-Script-for-Windows?label=)](https://github.com/farag2/Sophia-Script-for-Windows/blob/master/LICENSE)|[![](https://img.shields.io/github/last-commit/farag2/Sophia-Script-for-Windows?style=flat-square&label=)](https://github.com/farag2/Sophia-Script-for-Windows/graphs/code-frequency)|
|[windows-tools](https://github.com/jebofponderworthy/windows-tools#readme)|A toolset for improvement of performance of Windows desktop and server operating systems|[![](https://img.shields.io/github/languages/top/jebofponderworthy/windows-tools?color=pink&style=flat-square)](https://github.com/jebofponderworthy/windows-tools/graphs/contributors)|[![](https://flat.badgen.net/github/license/jebofponderworthy/windows-tools?label=)](https://github.com/jebofponderworthy/windows-tools/issues/7)|[![](https://img.shields.io/github/last-commit/jebofponderworthy/windows-tools?style=flat-square&label=)](https://github.com/jebofponderworthy/windows-tools/graphs/code-frequency)|
|[W11Boost](https://github.com/felikcat/W11Boost#readme)|Multi-choice Windows optimizer that prioritizes breaking nothing|[![](https://img.shields.io/github/languages/top/felikcat/W11Boost?color=pink&style=flat-square)](https://github.com/felikcat/W11Boost/graphs/contributors)|[![](https://flat.badgen.net/github/license/felikcat/W11Boost?label=)](https://github.com/felikcat/W11Boost/blob/master/LICENSE)|[![](https://flat.badgen.net/static/status/Archived/624711?label=)](https://github.com/felikcat/W11Boost/graphs/code-frequency)|
|[QuickRapidX](https://github.com/Good4Fox/QuickRapidX#readme)|Offers a wide range of features to help manage and optimize Windows 10 and 11 operating systems|[![](https://img.shields.io/github/languages/top/Good4Fox/QuickRapidX?color=pink&style=flat-square)](https://github.com/Good4Fox/QuickRapidX/graphs/contributors)|[![](https://flat.badgen.net/github/license/Good4Fox/QuickRapidX?label=)](https://github.com/Good4Fox/QuickRapidX/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/Good4Fox/QuickRapidX?style=flat-square&label=)](https://github.com/Good4Fox/QuickRapidX/graphs/code-frequency)|
|[Windows 11 Tweaker "Союз"](https://github.com/yoshinolalala/tweaker-soyuz#readme)|A powerful and easy-to-use tool to both improve the performance and personalize Windows 11 appearance|[![](https://img.shields.io/github/languages/top/yoshinolalala/tweaker-soyuz?color=pink&style=flat-square)](https://github.com/yoshinolalala/tweaker-soyuz/graphs/contributors)|[![](https://flat.badgen.net/github/license/yoshinolalala/tweaker-soyuz?label=)](https://github.com/yoshinolalala/tweaker-soyuz/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/yoshinolalala/tweaker-soyuz?style=flat-square&label=)](https://github.com/yoshinolalala/tweaker-soyuz/graphs/code-frequency)|
|[Windows_TweakerPro](https://github.com/saltypepper18/Windows_Tweaker#readme)|A small-sized but highly powerful program that allows you to fully optimize Windows 10-11|[![](https://img.shields.io/github/languages/top/saltypepper18/Windows_Tweaker?color=pink&style=flat-square)](https://github.com/saltypepper18/Windows_Tweaker/graphs/contributors)|[![](https://flat.badgen.net/github/license/saltypepper18/Windows_Tweaker?label=)](https://github.com/saltypepper18/Windows_Tweaker/issues/1)|[![](https://img.shields.io/github/last-commit/saltypepper18/Windows_Tweaker?style=flat-square&label=)](https://github.com/saltypepper18/Windows_Tweaker/graphs/code-frequency)|
|[WOTBO](https://github.com/oixro/WOTBO#readme)|Windows optimization tool|[![](https://img.shields.io/github/languages/top/oixro/WOTBO?color=pink&style=flat-square)](https://github.com/oixro/WOTBO/graphs/contributors)|[![](https://flat.badgen.net/github/license/oixro/WOTBO?label=)](https://github.com/oixro/WOTBO/issues/1)|[![](https://img.shields.io/github/last-commit/oixro/WOTBO?style=flat-square&label=)](https://github.com/oixro/WOTBO/graphs/code-frequency)|


### Debloaters [⌂](#-)
|Repository|Short description|Language|License|Last commit|
|:-:|:-:|:-:|:-:|:-:|
|[Debloat Windows11](https://github.com/cramaboule/Debloat_Windows11#readme)|Remove, uninstall unnecessary Windows 11 default programs, uninstall preinstalled apps|[![](https://img.shields.io/github/languages/top/cramaboule/Debloat_Windows11?color=pink&style=flat-square)](https://github.com/cramaboule/Debloat_Windows11/graphs/contributors)|[![](https://flat.badgen.net/github/license/cramaboule/Debloat_Windows11?label=)](https://github.com/cramaboule/Debloat_Windows11/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/cramaboule/Debloat_Windows11?style=flat-square&label=)](https://github.com/cramaboule/Debloat_Windows11/graphs/code-frequency)|
|[Windows Cleaner](https://github.com/codehacker47/Windows-Debloater#readme)|A script that optimizes and debloats Windows|[![](https://img.shields.io/github/languages/top/codehacker47/Windows-Debloater?color=pink&style=flat-square)](https://github.com/codehacker47/Windows-Debloater/graphs/contributors)|[![](https://flat.badgen.net/github/license/codehacker47/Windows-Debloater?label=)](https://github.com/codehacker47/Windows-Debloater/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/codehacker47/Windows-Debloater?style=flat-square&label=)](https://github.com/codehacker47/Windows-Debloater/graphs/code-frequency)|
|[Bloatynosy Nue](https://github.com/builtbybel/Bloatynosy#readme)|Tool for cleaning up and debloating Windows|[![](https://img.shields.io/github/languages/top/builtbybel/Bloatynosy?color=pink&style=flat-square)](https://github.com/builtbybel/Bloatynosy/graphs/contributors)|[![](https://flat.badgen.net/github/license/builtbybel/Bloatynosy?label=)](https://github.com/builtbybel/Bloatynosy/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/builtbybel/Bloatynosy?style=flat-square&label=)](https://github.com/builtbybel/Bloatynosy/graphs/code-frequency)|
|[WinScript](https://github.com/flick9000/winscript#readme)|Open-source tool to build your Windows 10/11 script from scratch|[![](https://img.shields.io/github/languages/top/flick9000/winscript?color=pink&style=flat-square)](https://github.com/flick9000/winscript/graphs/contributors)|[![](https://flat.badgen.net/github/license/flick9000/winscript?label=)](https://github.com/flick9000/winscript/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/flick9000/winscript?style=flat-square&label=)](https://github.com/flick9000/winscript/graphs/code-frequency)|
|[Rectify11](https://github.com/Rectify11/Installer#readme)|A Windows 11 modification which makes it more consistent|[![](https://img.shields.io/github/languages/top/Rectify11/Installer?color=pink&style=flat-square)](https://github.com/Rectify11/Installer/graphs/contributors)|[![](https://flat.badgen.net/github/license/Rectify11/Installer?label=)](https://github.com/Rectify11/Installer/blob/legacy-installer/LICENSE)|[![](https://img.shields.io/github/last-commit/Rectify11/Installer?style=flat-square&label=)](https://github.com/Rectify11/Installer/graphs/code-frequency)|
|[W1X Debloat](https://github.com/AdminVin/W1X-Debloat#readme)|A one click trick to cleaning up  Windows 10 & Windows 11|[![](https://img.shields.io/github/languages/top/AdminVin/W1X-Debloat?color=pink&style=flat-square)](https://github.com/AdminVin/W1X-Debloat/graphs/contributors)|[![](https://flat.badgen.net/github/license/AdminVin/W1X-Debloat?label=)](https://github.com/AdminVin/W1X-Debloat/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/AdminVin/W1X-Debloat?style=flat-square&label=)](https://github.com/AdminVin/W1X-Debloat/graphs/code-frequency)|
|[Auto Win10 Tweaker](https://github.com/vinioliveiras/Win10Tweaker#readme)|Remove all bloatware and tune your Windows 10|[![](https://img.shields.io/github/languages/top/vinioliveiras/Win10Tweaker?color=pink&style=flat-square)](https://github.com/vinioliveiras/Win10Tweaker/graphs/contributors)|[![](https://flat.badgen.net/github/license/vinioliveiras/Win10Tweaker?label=)](https://github.com/vinioliveiras/Win10Tweaker/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/vinioliveiras/Win10Tweaker?style=flat-square&label=)](https://github.com/vinioliveiras/Win10Tweaker/graphs/code-frequency)|
|[ITT (Install Tweaks Tool)](https://github.com/emadadel4/itt#-itt-install-tweaks-tool--)|Includes all useful Windows 10/11 Software and Windows Tweaks & Remove Bloatwares & Windows activation|[![](https://img.shields.io/github/languages/top/emadadel4/itt?color=pink&style=flat-square)](https://github.com/emadadel4/itt/graphs/contributors)|[![](https://flat.badgen.net/github/license/emadadel4/itt?label=)](https://github.com/emadadel4/itt/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/emadadel4/itt?style=flat-square&label=)](https://github.com/emadadel4/itt/graphs/code-frequency)|
|[Pure11](https://github.com/Orfeous/Pure11#readme)|Windows 11, minus the junk they thought you needed|[![](https://img.shields.io/github/languages/top/Orfeous/Pure11?color=pink&style=flat-square)](https://github.com/Orfeous/Pure11/graphs/contributors)|[![](https://flat.badgen.net/github/license/Orfeous/Pure11?label=)](https://github.com/Orfeous/Pure11/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/Orfeous/Pure11?style=flat-square&label=)](https://github.com/Orfeous/Pure11/graphs/code-frequency)|
|[Win11Debloat](https://github.com/RobertDevD/W11-W10-Debloater-Now#readme)|A simple, easy to use PowerShell script to remove pre-installed apps from Windows, disable telemetry, remove Bing from Windows search as well as perform various other changes to declutter and improve your Windows experience|[![](https://img.shields.io/github/languages/top/RobertDevD/W11-W10-Debloater-Now?color=pink&style=flat-square)](https://github.com/RobertDevD/W11-W10-Debloater-Now/graphs/contributors)|[![](https://flat.badgen.net/github/license/RobertDevD/W11-W10-Debloater-Now?label=)](https://github.com/RobertDevD/W11-W10-Debloater-Now/blob/main/LICENSE.txt)|[![](https://img.shields.io/github/last-commit/RobertDevD/W11-W10-Debloater-Now?style=flat-square&label=)](https://github.com/RobertDevD/W11-W10-Debloater-Now/graphs/code-frequency)|
|[Win11 Post Install PowerShell Script](https://github.com/vinod-unny-eit/Win11PostInstallPS#readme)|A Windows 11 (24H2) Post Install Script in PowerShell to customize your working environment|[![](https://img.shields.io/github/languages/top/vinod-unny-eit/Win11PostInstallPS?color=pink&style=flat-square)](https://github.com/vinod-unny-eit/Win11PostInstallPS/graphs/contributors)|[![](https://flat.badgen.net/github/license/vinod-unny-eit/Win11PostInstallPS?label=)](https://github.com/vinod-unny-eit/Win11PostInstallPS/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/vinod-unny-eit/Win11PostInstallPS?style=flat-square&label=)](https://github.com/vinod-unny-eit/Win11PostInstallPS/graphs/code-frequency)|
|[Debonk-Windows-11](https://github.com/Mugane/Debonk-Windows-11#readme)|Removes Garbage Apps & Settings on Windows 11|[![](https://img.shields.io/github/languages/top/Mugane/Debonk-Windows-11?color=pink&style=flat-square)](https://github.com/Mugane/Debonk-Windows-11/graphs/contributors)|[![](https://flat.badgen.net/badge/license/Other/blue?label=)](https://github.com/Mugane/Debonk-Windows-11/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/Mugane/Debonk-Windows-11?style=flat-square&label=)](https://github.com/Mugane/Debonk-Windows-11/graphs/code-frequency)|
|[WinTools](https://github.com/levicm/win-tools#readme)|This is the a set of Windows 10/11 tool scripts, from a creation of multiple debloat scripts and gists from github|[![](https://img.shields.io/github/languages/top/levicm/win-tools?color=pink&style=flat-square)](https://github.com/levicm/win-tools/graphs/contributors)|[![](https://flat.badgen.net/github/license/levicm/win-tools?label=)](https://github.com/levicm/win-tools/issues/1)|[![](https://img.shields.io/github/last-commit/levicm/win-tools?style=flat-square&label=)](https://github.com/levicm/win-tools/graphs/code-frequency)|
|[XToolbox](https://codeberg.org/nxr/xtoolbox#readme)|A collection of 150+ Windows 10/11 optimization and tweaking apps|[![](https://img.shields.io/github/languages/top/nyxiereal/XToolbox?color=pink&style=flat-square)](https://github.com/nyxiereal/XToolbox/graphs/contributors)|[![](https://flat.badgen.net/github/license/nyxiereal/XToolbox?label=)](https://github.com/nyxiereal/XToolbox/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/nyxiereal/XToolbox?style=flat-square&label=)](https://github.com/nyxiereal/XToolbox/graphs/code-frequency)|



### Setupers [⌂](#-)
|Repository|Short description|Language|License|Last commit|
|:-:|:-:|:-:|:-:|:-:|
|[Orange Bosster](https://github.com/adasjusk/Orange-Booster#readme)|It's for debloating, increasing privacy and enabling some tweaks in Windows 10/11|[![](https://img.shields.io/github/languages/top/adasjusk/Orange-Booster?color=pink&style=flat-square)](https://github.com/adasjusk/Orange-Booster/graphs/contributors)|[![](https://flat.badgen.net/github/license/adasjusk/Orange-Booster?label=)](https://github.com/adasjusk/Orange-Booster/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/adasjusk/Orange-Booster?style=flat-square&label=)](https://github.com/adasjusk/Orange-Booster/graphs/code-frequency)|
|[Simplify11](https://github.com/emylfy/simplify11#readme)|Simpler way to setup your Windows (Individual Perfomance & Privacy tweaks, Space cleaner, App Installer)|[![](https://img.shields.io/github/languages/top/emylfy/simplify11?color=pink&style=flat-square)](https://github.com/emylfy/simplify11/graphs/contributors)|[![](https://flat.badgen.net/github/license/emylfy/simplify11?label=)](https://github.com/emylfy/simplify11/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/emylfy/simplify11?style=flat-square&label=)](https://github.com/emylfy/simplify11/graphs/code-frequency)|
|[WinConfigs](https://github.com/fr0st-iwnl/WinConfigs#readme)|A script to simplify Windows setup by automating software installation and system tweaks|[![](https://img.shields.io/github/languages/top/fr0st-iwnl/WinConfigs?color=pink&style=flat-square)](https://github.com/fr0st-iwnl/WinConfigs/graphs/contributors)|[![](https://flat.badgen.net/github/license/fr0st-iwnl/WinConfigs?label=)](https://github.com/fr0st-iwnl/WinConfigs/blob/master/LICENSE)|[![](https://img.shields.io/github/last-commit/fr0st-iwnl/WinConfigs?style=flat-square&label=)](https://github.com/fr0st-iwnl/WinConfigs/graphs/code-frequency)|
|[Awesome Windows Tweaks](https://github.com/Zalexanninev15/awesome-windows-tweaks#readme)|An incredible amount of scripts, tweaks, programs and everything else for the initial setup of Windows.|[![](https://img.shields.io/github/languages/top/Zalexanninev15/awesome-windows-tweaks?color=pink&style=flat-square)](https://github.com/Zalexanninev15/awesome-windows-tweaks/graphs/contributors)|[![](https://flat.badgen.net/github/license/Zalexanninev15/awesome-windows-tweaks?label=)](https://github.com/Zalexanninev15/awesome-windows-tweaks/issues/1)|[![](https://img.shields.io/github/last-commit/Zalexanninev15/awesome-windows-tweaks?style=flat-square&label=)](https://github.com/Zalexanninev15/awesome-windows-tweaks/graphs/code-frequency)|
|[ASX-Hub](https://github.com/ALFiX01/ASX-Hub#readme)|Free Windows 10/11 utility to increase FPS, simplify OS setup, download programs, etc.|[![](https://img.shields.io/github/languages/top/ALFiX01/ASX-Hub?color=pink&style=flat-square)](https://github.com/ALFiX01/ASX-Hub/graphs/contributors)|[![](https://flat.badgen.net/github/license/ALFiX01/ASX-Hub?label=)](https://github.com/ALFiX01/ASX-Hub/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/ALFiX01/ASX-Hub?style=flat-square&label=)](https://github.com/ALFiX01/ASX-Hub/graphs/code-frequency)|
|[TweakList](https://github.com/couleur-tweak-tips/TweakList#readme)|Versatile PowerShell module that automate various post-install jobs you waste time on|[![](https://img.shields.io/github/languages/top/couleur-tweak-tips/TweakList?color=pink&style=flat-square)](https://github.com/couleur-tweak-tips/TweakList/graphs/contributors)|[![](https://flat.badgen.net/github/license/couleur-tweak-tips/TweakList?label=)](https://github.com/couleur-tweak-tips/TweakList/blob/master/LICENSE)|[![](https://img.shields.io/github/last-commit/couleur-tweak-tips/TweakList?style=flat-square&label=)](https://github.com/couleur-tweak-tips/TweakList/graphs/code-frequency)|
|[Windows Panther](https://github.com/JamesMinoucha/WindowsPanther#readme)|A autounattend.xml made to debloat and optimize Windows|[![](https://img.shields.io/github/languages/top/JamesMinoucha/WindowsPanther?color=pink&style=flat-square)](https://github.com/JamesMinoucha/WindowsPanther/graphs/contributors)|[![](https://flat.badgen.net/github/license/JamesMinoucha/WindowsPanther?label=)](https://github.com/JamesMinoucha/WindowsPanther/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/JamesMinoucha/WindowsPanther?style=flat-square&label=)](https://github.com/JamesMinoucha/WindowsPanther/graphs/code-frequency)|
|[after-format](https://github.com/caglaryalcin/after-format#readme)|If you have just formatted your Windows 11 computer, you can run this script for a better Windows experience|[![](https://img.shields.io/github/languages/top/caglaryalcin/after-format?color=pink&style=flat-square)](https://github.com/caglaryalcin/after-format/graphs/contributors)|[![](https://flat.badgen.net/github/license/caglaryalcin/after-format?label=)](https://github.com/caglaryalcin/after-format/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/caglaryalcin/after-format?style=flat-square&label=)](https://github.com/caglaryalcin/after-format/graphs/code-frequency)|
|[Windows10-Postinstall](https://github.com/r33int/Windows10-Postinstall#readme)|Scripts & programs to optimize and debloat new Windows 10 and Windows 11 installations|[![](https://img.shields.io/github/languages/top/r33int/Windows10-Postinstall?color=pink&style=flat-square)](https://github.com/r33int/Windows10-Postinstall/graphs/contributors)|[![](https://flat.badgen.net/github/license/r33int/Windows10-Postinstall?label=)](https://github.com/r33int/Windows10-Postinstall/blob/main/COPYING)|[![](https://img.shields.io/github/last-commit/r33int/Windows10-Postinstall?style=flat-square&label=)](https://github.com/r33int/Windows10-Postinstall/graphs/code-frequency)|
|[Chris Titus Tech's Windows Utility](https://github.com/ChrisTitusTech/winutil#readme)|A compilation of tasks meant to streamline installs, debloat with tweaks, troubleshoot with config, and fix Windows updates|[![](https://img.shields.io/github/languages/top/ChrisTitusTech/winutil?color=pink&style=flat-square)](https://github.com/ChrisTitusTech/winutil/graphs/contributors)|[![](https://flat.badgen.net/github/license/ChrisTitusTech/winutil?label=)](https://github.com/ChrisTitusTech/winutil/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/ChrisTitusTech/winutil?style=flat-square&label=)](https://github.com/ChrisTitusTech/winutil/graphs/code-frequency)|
|[LazyBlaze](https://github.com/SuperBoots/lazyblaze#readme)|Built around PowerShell scripts for quickly getting a new Windows 11 machine populated with all your favorite programs and customized to your liking|[![](https://img.shields.io/github/languages/top/SuperBoots/lazyblaze?color=pink&style=flat-square)](https://github.com/SuperBoots/lazyblaze/graphs/contributors)|[![](https://flat.badgen.net/github/license/SuperBoots/lazyblaze?label=)](https://github.com/SuperBoots/lazyblaze/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/SuperBoots/lazyblaze?style=flat-square&label=)](https://github.com/SuperBoots/lazyblaze/graphs/code-frequency)|
|[UnattendedWinstall](https://github.com/memstechtips/UnattendedWinstall#readme)|Personalized Unattended Answer Files that helps automatically debloat and customize Windows 10 & 11 during the installation process|[![](https://img.shields.io/github/languages/top/memstechtips/UnattendedWinstall?color=pink&style=flat-square)](https://github.com/memstechtips/UnattendedWinstall/graphs/contributors)|[![](https://flat.badgen.net/github/license/memstechtips/UnattendedWinstall?label=)](https://github.com/memstechtips/UnattendedWinstall/blob/main/LICENSE.md)|[![](https://img.shields.io/github/last-commit/memstechtips/UnattendedWinstall?style=flat-square&label=)](https://github.com/memstechtips/UnattendedWinstall/graphs/code-frequency)|
|[WindowsMize](https://github.com/agadiffe/WindowsMize#readme)|PowerShell script to automate and customize the configuration of Windows: Settings, apps uninstall/install/settings, minimize telemetry, disable services/scheduled tasks, RamDisk, and other tweaks|[![](https://img.shields.io/github/languages/top/agadiffe/WindowsMize?color=pink&style=flat-square)](https://github.com/agadiffe/WindowsMize/graphs/contributors)|[![](https://flat.badgen.net/github/license/agadiffe/WindowsMize?label=)](https://github.com/agadiffe/WindowsMize/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/agadiffe/WindowsMize?style=flat-square&label=)](https://github.com/agadiffe/WindowsMize/graphs/code-frequency)|
|[ZOICWARE](https://github.com/zoicware/ZOICWARE#readme)|A Powershell script to tweak and customize Windows 10 and 11|[![](https://img.shields.io/github/languages/top/zoicware/ZOICWARE?color=pink&style=flat-square)](https://github.com/zoicware/ZOICWARE/graphs/contributors)|[![](https://flat.badgen.net/github/license/zoicware/ZOICWARE?label=)](https://github.com/zoicware/ZOICWARE/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/zoicware/ZOICWARE?style=flat-square&label=)](https://github.com/zoicware/ZOICWARE/graphs/code-frequency)|
|[setup_scripts_for_windows](https://github.com/EffiOvadia/setup_scripts_for_windows#readme)|PowerShell setup scripts for Windows 10/11 operating system |[![](https://img.shields.io/github/languages/top/EffiOvadia/setup_scripts_for_windows?color=pink&style=flat-square)](https://github.com/EffiOvadia/setup_scripts_for_windows/graphs/contributors)|[![](https://flat.badgen.net/github/license/EffiOvadia/setup_scripts_for_windows?label=)](https://github.com/EffiOvadia/setup_scripts_for_windows/issues/1)|[![](https://img.shields.io/github/last-commit/EffiOvadia/setup_scripts_for_windows?style=flat-square&label=)](https://github.com/EffiOvadia/setup_scripts_for_windows/graphs/code-frequency)|
|[windows_config_scripts](https://github.com/rondonit/windows_config_scripts#readme)|PowerShell scripts to automate configurations and optimize Windows settings|[![](https://img.shields.io/github/languages/top/rondonit/windows_config_scripts?color=pink&style=flat-square)](https://github.com/rondonit/windows_config_scripts/graphs/contributors)|[![](https://flat.badgen.net/github/license/rondonit/windows_config_scripts?label=)](https://github.com/rondonit/windows_config_scripts/issues/1)|[![](https://img.shields.io/github/last-commit/rondonit/windows_config_scripts?style=flat-square&label=)](https://github.com/rondonit/windows_config_scripts/graphs/code-frequency)|
|[AutoUnattend.xml: Your Ultimate Windows 11 Installation Automation Tool](https://github.com/Deffz-Finesse/Win11-Debloat#readme)|A streamlined and fully automated Windows 11 installation setup that removes bloatware, optimizes performance, and bypasses hardware requirements|[![](https://img.shields.io/github/languages/top/Deffz-Finesse/Win11-Debloat?color=pink&style=flat-square)](https://github.com/Deffz-Finesse/Win11-Debloat/graphs/contributors)|[![](https://flat.badgen.net/github/license/Deffz-Finesse/Win11-Debloat?label=)](https://github.com/Deffz-Finesse/Win11-Debloat/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/Deffz-Finesse/Win11-Debloat?style=flat-square&label=)](https://github.com/Deffz-Finesse/Win11-Debloat/graphs/code-frequency)|
|[WindowsTweaks](https://github.com/acuna-public/WindowsTweaks#readme)|A Regedit config file for fine Windows tuning|[![](https://img.shields.io/github/languages/top/acuna-public/WindowsTweaks?color=pink&style=flat-square)](https://github.com/acuna-public/WindowsTweaks/graphs/contributors)|[![](https://flat.badgen.net/github/license/acuna-public/WindowsTweaks?label=)](https://github.com/acuna-public/WindowsTweaks/issues/1)|[![](https://img.shields.io/github/last-commit/acuna-public/WindowsTweaks?style=flat-square&label=)](https://github.com/acuna-public/WindowsTweaks/graphs/code-frequency)|



### Privacy [⌂](#-)
|Repository|Short description|Language|License|Last commit|
|:-:|:-:|:-:|:-:|:-:|
|[Windows 11 Privacy Optimizer](https://github.com/HerrTaeubler/Win11-privacy-tool#readme)|A PowerShell script to optimize privacy settings in Windows 11|[![](https://img.shields.io/github/languages/top/HerrTaeubler/Win11-privacy-tool?color=pink&style=flat-square)](https://github.com/HerrTaeubler/Win11-privacy-tool/graphs/contributors)|[![](https://flat.badgen.net/github/license/HerrTaeubler/Win11-privacy-tool?label=)](https://github.com/HerrTaeubler/Win11-privacy-tool/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/HerrTaeubler/Win11-privacy-tool?style=flat-square&label=)](https://github.com/HerrTaeubler/Win11-privacy-tool/graphs/code-frequency)|
|[DebloatAndSecurizeW11](https://github.com/JulienVB/DebloatAndSecurizeW11#readme)|Windows 11 Hardening Script|[![](https://img.shields.io/github/languages/top/JulienVB/DebloatAndSecurizeW11?color=pink&style=flat-square)](https://github.com/JulienVB/DebloatAndSecurizeW11/graphs/contributors)|[![](https://flat.badgen.net/github/license/JulienVB/DebloatAndSecurizeW11?label=)](https://github.com/JulienVB/DebloatAndSecurizeW11/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/JulienVB/DebloatAndSecurizeW11?style=flat-square&label=)](https://github.com/JulienVB/DebloatAndSecurizeW11/graphs/code-frequency)|


### Specific [⌂](#-)
|Repository|Short description|Language|License|Last commit|
|:-:|:-:|:-:|:-:|:-:|
|[FPS-Boost](https://github.com/JitRRky/FPS-Boost#readme)|A powerful tool designed to enhance frame rates and optimize graphics settings seamlessly|[![](https://img.shields.io/github/languages/top/JitRRky/FPS-Boost?color=pink&style=flat-square)](https://github.com/JitRRky/FPS-Boost/graphs/contributors)|[![](https://flat.badgen.net/github/license/JitRRky/FPS-Boost?label=)](https://github.com/JitRRky/FPS-Boost/blob/master/LICENSE)|[![](https://img.shields.io/github/last-commit/JitRRky/FPS-Boost?style=flat-square&label=)](https://github.com/JitRRky/FPS-Boost/graphs/code-frequency)|
|[WindowsOptimizer](https://github.com/Jomaxsoec/WindowsOptimizer#readme)|Cleans temporary files (Temp, Prefetch, Recycle Bin),Clears Windows Update cache,Flushes DNS cache,Optionally restarts Explorer for changes to take effect|[![](https://img.shields.io/github/languages/top/Jomaxsoec/WindowsOptimizer?color=pink&style=flat-square)](https://github.com/Jomaxsoec/WindowsOptimizer/graphs/contributors)|[![](https://flat.badgen.net/github/license/Jomaxsoec/WindowsOptimizer?label=)](https://github.com/Jomaxsoec/WindowsOptimizer/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/Jomaxsoec/WindowsOptimizer?style=flat-square&label=)](https://github.com/Jomaxsoec/WindowsOptimizer/graphs/code-frequency)|
|[windows-dev-box-setup-scripts](https://github.com/microsoft/windows-dev-box-setup-scripts#readme)|Scripts to simplify setting up a Windows developer box|[![](https://img.shields.io/github/languages/top/microsoft/windows-dev-box-setup-scripts?color=pink&style=flat-square)](https://github.com/microsoft/windows-dev-box-setup-scripts/graphs/contributors)|[![](https://flat.badgen.net/github/license/microsoft/windows-dev-box-setup-scripts?label=)](https://github.com/microsoft/windows-dev-box-setup-scripts/blob/master/LICENSE)|[![](https://img.shields.io/github/last-commit/microsoft/windows-dev-box-setup-scripts?style=flat-square&label=)](https://github.com/microsoft/windows-dev-box-setup-scripts/graphs/code-frequency)|
|[Microsoft Edge Uninstallers](https://github.com/ShadowWhisperer/Remove-MS-Edge#readme)|Uninstall Microsoft Edge silently, through an executable or batch script.|[![](https://img.shields.io/github/languages/top/ShadowWhisperer/Remove-MS-Edge?color=pink&style=flat-square)](https://github.com/ShadowWhisperer/Remove-MS-Edge/graphs/contributors)|[![](https://flat.badgen.net/github/license/ShadowWhisperer/Remove-MS-Edge?label=)](https://github.com/ShadowWhisperer/Remove-MS-Edge/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/ShadowWhisperer/Remove-MS-Edge?style=flat-square&label=)](https://github.com/ShadowWhisperer/Remove-MS-Edge/graphs/code-frequency)|
|[NetBoost](https://github.com/donnauvwas/netboost#readme)|Optimizes network settings to increase download and upload speeds on Windows|[![](https://img.shields.io/github/languages/top/donnauvwas/netboost?color=pink&style=flat-square)](https://github.com/donnauvwas/netboost/graphs/contributors)|[![](https://flat.badgen.net/github/license/donnauvwas/netboost?label=)](https://github.com/donnauvwas/netboost/issues/17)|[![](https://img.shields.io/github/last-commit/donnauvwas/netboost?style=flat-square&label=)](https://github.com/donnauvwas/netboost/graphs/code-frequency)|
|[PowerTune](https://github.com/ruthijkis/powertune#readme)|Optimizes power settings for performance or energy saving based on current user activity on Windows.|[![](https://img.shields.io/github/languages/top/ruthijkis/powertune?color=pink&style=flat-square)](https://github.com/ruthijkis/powertune/graphs/contributors)|[![](https://flat.badgen.net/github/license/ruthijkis/powertune?label=)](https://github.com/ruthijkis/powertune/issues/15)|[![](https://img.shields.io/github/last-commit/ruthijkis/powertune?style=flat-square&label=)](https://github.com/ruthijkis/powertune/graphs/code-frequency)|
|[TaskOptimizer](https://github.com/sarahuptma/taskoptimizer#readme)|Analyzes and optimizes currently running tasks to improve system efficiency on Windows|[![](https://img.shields.io/github/languages/top/sarahuptma/taskoptimizer?color=pink&style=flat-square)](https://github.com/sarahuptma/taskoptimizer/graphs/contributors)|[![](https://flat.badgen.net/github/license/sarahuptma/taskoptimizer?label=)](https://github.com/sarahuptma/taskoptimizer/issues/14)|[![](https://img.shields.io/github/last-commit/sarahuptma/taskoptimizer?style=flat-square&label=)](https://github.com/sarahuptma/taskoptimizer/graphs/code-frequency)|
|[Windows-Optimizer-Project](https://github.com/WINDOWS-OPTIMIZER-PROJECT/WINDOWS-OPTIMIZER#readme)|Adapts the different Windows caches (i.e. memory areas and the size of the paging file)  automatically to the integrated hardware such as the main memory|[![](https://img.shields.io/github/languages/top/WINDOWS-OPTIMIZER-PROJECT/WINDOWS-OPTIMIZER?color=pink&style=flat-square)](https://github.com/WINDOWS-OPTIMIZER-PROJECT/WINDOWS-OPTIMIZER/graphs/contributors)|[![](https://flat.badgen.net/github/license/WINDOWS-OPTIMIZER-PROJECT/WINDOWS-OPTIMIZER?label=)](https://github.com/WINDOWS-OPTIMIZER-PROJECT/WINDOWS-OPTIMIZER/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/WINDOWS-OPTIMIZER-PROJECT/WINDOWS-OPTIMIZER?style=flat-square&label=)](https://github.com/WINDOWS-OPTIMIZER-PROJECT/WINDOWS-OPTIMIZER/graphs/code-frequency)|



### Other [⌂](#-)
|Repository|Short description|Language|License|Last commit|
|:-:|:-:|:-:|:-:|:-:|
|[Windows 10/11 Simplifier](https://github.com/mattreecebentley/Windows-10-11-Simplifier#readme)|A script for automating simplifications and maintenance|[![](https://img.shields.io/github/languages/top/mattreecebentley/Windows-10-11-Simplifier?color=pink&style=flat-square)](https://github.com/mattreecebentley/Windows-10-11-Simplifier/graphs/contributors)|[<img src="https://mirrors.creativecommons.org/presskit/buttons/88x31/png/by.png" height="20">](https://github.com/mattreecebentley/Windows-10-11-Simplifier/blob/master/license.md)|[![](https://img.shields.io/github/last-commit/mattreecebentley/Windows-10-11-Simplifier?style=flat-square&label=)](https://github.com/mattreecebentley/Windows-10-11-Simplifier/graphs/code-frequency)|
|[NightBox](https://github.com/DarkMod3/NightBox#readme)|A simple but essential utility for Windows, with several options such as applications, tools, optimizations, customizations, among others|[![](https://img.shields.io/github/languages/top/DarkMod3/NightBox?color=pink&style=flat-square)](https://github.com/DarkMod3/NightBox/graphs/contributors)|[![](https://flat.badgen.net/github/license/DarkMod3/NightBox?label=)](https://github.com/DarkMod3/NightBox/blob/Main/LICENSE)|[![](https://img.shields.io/github/last-commit/DarkMod3/NightBox?style=flat-square&label=)](https://github.com/DarkMod3/NightBox/graphs/code-frequency)|
|[Windows Repair and Optimization Scripts](https://github.com/tboy1337/Repair-Windows#readme)|A collection of batch scripts to repair and optimize Windows systems|[![](https://img.shields.io/github/languages/top/tboy1337/Repair-Windows?color=pink&style=flat-square)](https://github.com/tboy1337/Repair-Windows/graphs/contributors)|[![](https://flat.badgen.net/github/license/tboy1337/Repair-Windows?label=)](https://github.com/tboy1337/Repair-Windows/blob/main/LICENSE.txt)|[![](https://img.shields.io/github/last-commit/tboy1337/Repair-Windows?style=flat-square&label=)](https://github.com/tboy1337/Repair-Windows/graphs/code-frequency)|
|[Auto-Tune](https://github.com/RpJect/Auto-Tune#readme)|Program Uses Microsoft Windows Built-in Tools designed to optimize and fix various issues on a Windows system|[![](https://img.shields.io/github/languages/top/RpJect/Auto-Tune?color=pink&style=flat-square)](https://github.com/RpJect/Auto-Tune/graphs/contributors)|[![](https://flat.badgen.net/github/license/RpJect/Auto-Tune?label=)](https://github.com/RpJect/Auto-Tune/issues/1)|[![](https://img.shields.io/github/last-commit/RpJect/Auto-Tune?style=flat-square&label=)](https://github.com/RpJect/Auto-Tune/graphs/code-frequency)|
|[Tweaks-Configurations-Troubleshooting](https://github.com/SecretlySpy/Tweaks-Configurations-Troubleshooting#readme)|These files are made for Windows and Linux to make the system run smoothly with customized changes|[![](https://img.shields.io/github/languages/top/SecretlySpy/Tweaks-Configurations-Troubleshooting?color=pink&style=flat-square)](https://github.com/SecretlySpy/Tweaks-Configurations-Troubleshooting/graphs/contributors)|[![](https://flat.badgen.net/github/license/SecretlySpy/Tweaks-Configurations-Troubleshooting?label=)](https://github.com/SecretlySpy/Tweaks-Configurations-Troubleshooting/issues/1)|[![](https://img.shields.io/github/last-commit/SecretlySpy/Tweaks-Configurations-Troubleshooting?style=flat-square&label=)](https://github.com/SecretlySpy/Tweaks-Configurations-Troubleshooting/graphs/code-frequency)|
|[PASPAS](https://github.com/berkaygediz/PASPAS#readme)|A fast and efficient multi-threaded analysis and cleanup tool designed to accelerate system maintenance tasks|[![](https://img.shields.io/github/languages/top/berkaygediz/PASPAS?color=pink&style=flat-square)](https://github.com/berkaygediz/PASPAS/graphs/contributors)|[![](https://flat.badgen.net/github/license/berkaygediz/PASPAS?label=)](https://github.com/berkaygediz/PASPAS/blob/master/LICENSE)|[![](https://img.shields.io/github/last-commit/berkaygediz/PASPAS/master?style=flat-square&label=)](https://github.com/berkaygediz/PASPAS/graphs/code-frequency)|
|[GamingPCSetup](https://github.com/djdallmann/GamingPCSetup#readme)|A research and evidence based approach guide to optimizing your gaming PC, configuration and setup|[![](https://img.shields.io/github/languages/top/djdallmann/GamingPCSetup?color=pink&style=flat-square)](https://github.com/djdallmann/GamingPCSetup/graphs/contributors)|[![](https://flat.badgen.net/github/license/djdallmann/GamingPCSetup?label=)](https://github.com/djdallmann/GamingPCSetup/blob/master/LICENSE)|[![](https://img.shields.io/github/last-commit/djdallmann/GamingPCSetup?style=flat-square&label=)](https://github.com/djdallmann/GamingPCSetup/graphs/code-frequency)|
|[PC Maintenance & Troubleshooting Toolkit Guide](https://github.com/Cybersecsolution/PCMTT#readme)|A comprehensive PowerShell script designed to optimize system performance, troubleshoot issues, and improve security|[![](https://img.shields.io/github/languages/top/Cybersecsolution/PCMTT?color=pink&style=flat-square)](https://github.com/Cybersecsolution/PCMTT/graphs/contributors)|[![](https://flat.badgen.net/github/license/Cybersecsolution/PCMTT?label=)](https://github.com/Cybersecsolution/PCMTT/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/Cybersecsolution/PCMTT?style=flat-square&label=)](https://github.com/Cybersecsolution/PCMTT/graphs/code-frequency)|
|[PowerShell](https://github.com/bonguides25/PowerShell#readme)|-|[![](https://img.shields.io/github/languages/top/bonguides25/PowerShell?color=pink&style=flat-square)](https://github.com/bonguides25/PowerShell/graphs/contributors)|[![](https://flat.badgen.net/github/license/bonguides25/PowerShell?label=)](https://github.com/bonguides25/PowerShell/issues/2)|[![](https://img.shields.io/github/last-commit/bonguides25/PowerShell?style=flat-square&label=)](https://github.com/bonguides25/PowerShell/graphs/code-frequency)|
|[system-optimizer](https://github.com/weppyk/system-optimizer#readme)|A repository for optimizing Windows, Linux, and macOS systems|[![](https://img.shields.io/github/languages/top/weppyk/system-optimizer?color=pink&style=flat-square)](https://github.com/weppyk/system-optimizer/graphs/contributors)|[![](https://flat.badgen.net/github/license/weppyk/system-optimizer?label=)](https://github.com/weppyk/system-optimizer/issues/1)|[![](https://img.shields.io/github/last-commit/weppyk/system-optimizer?style=flat-square&label=)](https://github.com/weppyk/system-optimizer/graphs/code-frequency)|
|[Windows-Tweaker-Resources](https://github.com/FyumiSownz/Windows-Tweaker-Resources#readme)|-|[![](https://img.shields.io/github/languages/top/FyumiSownz/Windows-Tweaker-Resources?color=pink&style=flat-square)](https://github.com/FyumiSownz/Windows-Tweaker-Resources/graphs/contributors)|[![](https://flat.badgen.net/github/license/FyumiSownz/Windows-Tweaker-Resources?label=)](https://github.com/FyumiSownz/Windows-Tweaker-Resources/issues/1)|[![](https://img.shields.io/github/last-commit/FyumiSownz/Windows-Tweaker-Resources?style=flat-square&label=)](https://github.com/FyumiSownz/Windows-Tweaker-Resources/graphs/code-frequency)|
|[WinFixer Ultimate](https://github.com/FahadMAlsamiti/WinFixer-Ultimate#readme)|A powerful tool designed to repair, clean, and optimize your Windows system|[![](https://img.shields.io/github/languages/top/FahadMAlsamiti/WinFixer-Ultimate?color=pink&style=flat-square)](https://github.com/FahadMAlsamiti/WinFixer-Ultimate/graphs/contributors)|[![](https://flat.badgen.net/github/license/FahadMAlsamiti/WinFixer-Ultimate?label=)](https://github.com/FahadMAlsamiti/WinFixer-Ultimate/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/FahadMAlsamiti/WinFixer-Ultimate?style=flat-square&label=)](https://github.com/FahadMAlsamiti/WinFixer-Ultimate/graphs/code-frequency)|
|[WinTuning](https://github.com/DevSentinel/WinTuning#readme)|A documentation for tuning Windows|[![](https://img.shields.io/github/languages/top/DevSentinel/WinTuning?color=pink&style=flat-square)](https://github.com/DevSentinel/WinTuning/graphs/contributors)|[![](https://flat.badgen.net/github/license/DevSentinel/WinTuning?label=)](https://github.com/DevSentinel/WinTuning/issues/1)|[![](https://img.shields.io/github/last-commit/DevSentinel/WinTuning?style=flat-square&label=)](https://github.com/DevSentinel/WinTuning/graphs/code-frequency)|
|[Windows Tweaker Tool](https://github.com/xize/WSTT#readme)|A easy way to tweak windows and its security policies|[![](https://img.shields.io/github/languages/top/xize/WSTT?color=pink&style=flat-square)](https://github.com/xize/WSTT/graphs/contributors)|[![](https://flat.badgen.net/github/license/xize/WSTT?label=)](https://github.com/xize/WSTT/blob/master/LICENSE)|[![](https://img.shields.io/github/last-commit/xize/WSTT?style=flat-square&label=)](https://github.com/xize/WSTT/graphs/code-frequency)|
|[Fixyfier](https://github.com/arisvardakas/Fixyfier#readme)|A user-friendly toolkit for PC maintenance, optimization, and troubleshooting|[![](https://img.shields.io/github/languages/top/arisvardakas/Fixyfier?color=pink&style=flat-square)](https://github.com/arisvardakas/Fixyfier/graphs/contributors)|[![](https://flat.badgen.net/badge/license/Other/blue?label=)](https://github.com/arisvardakas/Fixyfier/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/arisvardakas/Fixyfier?style=flat-square&label=)](https://github.com/arisvardakas/Fixyfier/graphs/code-frequency)|
|[Universal PC Optimization](https://github.com/NazgulCoder/Universal-PC-Optimization#readme)|A wealth of valuable information on PC tweaking and fine-tuning, helping you optimize every aspect of system's performance|[![](https://img.shields.io/github/languages/top/NazgulCoder/Universal-PC-Optimization?color=pink&style=flat-square)](https://github.com/NazgulCoder/Universal-PC-Optimization/graphs/contributors)|[![](https://flat.badgen.net/github/license/NazgulCoder/Universal-PC-Optimization?label=)](https://github.com/NazgulCoder/Universal-PC-Optimization/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/NazgulCoder/Universal-PC-Optimization?style=flat-square&label=)](https://github.com/NazgulCoder/Universal-PC-Optimization/graphs/code-frequency)|
|[Windows Optimizations & Adjustments](https://github.com/SD-ITLab/OptimizeWindows#windows-optimizations--adjustments)|Directory for Windows ISO-Tweaks|[![](https://img.shields.io/github/languages/top/SD-ITLab/OptimizeWindows?color=pink&style=flat-square)](https://github.com/SD-ITLab/OptimizeWindows/graphs/contributors)|[![](https://flat.badgen.net/github/license/SD-ITLab/OptimizeWindows?label=)](https://github.com/SD-ITLab/OptimizeWindows/blob/main/LICENSE)|[![](https://img.shields.io/github/last-commit/SD-ITLab/OptimizeWindows?style=flat-square&label=)](https://github.com/SD-ITLab/OptimizeWindows/graphs/code-frequency)|
|[Windows 11 system tuning settings](https://github.com/jash-git/Windows-11-system-tuning-settings#readme)|Windows 11 system tuning settings|[![](https://img.shields.io/github/languages/top/jash-git/Windows-11-system-tuning-settings?color=pink&style=flat-square)](https://github.com/jash-git/Windows-11-system-tuning-settings/graphs/contributors)|[![](https://flat.badgen.net/github/license/jash-git/Windows-11-system-tuning-settings?label=)](https://github.com/jash-git/Windows-11-system-tuning-settings/issues/1)|[![](https://img.shields.io/github/last-commit/jash-git/Windows-11-system-tuning-settings?style=flat-square&label=)](https://github.com/jash-git/Windows-11-system-tuning-settings/graphs/code-frequency)|
